[package]
name = "irmaseal-pkg"
version = "0.1.0"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"

[dependencies]
irmaseal-core = { path = "../irmaseal-core", default-features = false }
ibe = "0.1.3"
irma = "0.0.1"

actix-rt = "1.1.1"
actix-web = { version = "2.0.0", default-features = false }
actix-cors = "0.2.0"
arrayref = "0.3.5"
subtle = "2.1.1"
clap = { version = "2.33.0", features = ["yaml"] }
rand = "0.7.0"
serde_json = "1.0.40"
futures = "0.1.28"